### ISSUE TITLE
Exception in thread main_loop after pulling fresh master

### ISSUE THREAD

**Issue by AndKe** [Dronecode/MAVProxy#222]
I had it working just fine, see fresh pull request - then I updated master, and got problems:
The crash happens only when there is incoming mavlink data , not when starting mavproxy w(o connection.

```

Connect 0.0.0.0:14550 source_system=255
Log Directory: 
Telemetry log: mav.tlog
Waiting for heartbeat from 0.0.0.0:14550
 MAV> Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/mavproxy.py", line 712, in main_loop
    master.wait_heartbeat()
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 374, in wait_heartbeat
    return self.recv_match(type='HEARTBEAT', blocking=blocking)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 339, in recv_match
    m = self.recv_msg()
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 843, in recv_msg
    msg = self.mav.parse_buffer(s)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/dialects/v10/ardupilotmega.py", line 8009, in parse_buffer
    m = self.parse_char(s)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/dialects/v10/ardupilotmega.py", line 7966, in parse_char
    self.__callbacks(m)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/dialects/v10/ardupilotmega.py", line 7943, in __callbacks
    self.callback(msg, *self.callback_args, **self.callback_kwargs)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_link.py", line 247, in master_callback
    if sysid in self.mpstate.sysid_outputs:
AttributeError: 'MPState' object has no attribute 'sysid_outputs'



```

**Comment by AndKe** [comment]
..due to mavlink in two places on computer, not updated the one in path
