### ISSUE TITLE
Incomplete string input on command line freezes SITL

### ISSUE THREAD

**Issue by mday299** [Dronecode/MAVProxy#293]
In SITL:

If I input a ' character at the MAVProxy prompt (or a command with an accidental trailing '), ArduPlane ceases accepting commands and the map and console become frozen.  Error at MAVProxy is:

MANUAL> '
MANUAL> Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/mavproxy.py", line 731, in main_loop
    process_stdin(c)
  File "/usr/local/bin/mavproxy.py", line 447, in process_stdin
    args = shlex.split(line)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by mday299** [comment]
I had an older verson of MAVProxy and this appears to be fixed in current master. 

HOWEVER, using a " character does still cause the same problem:

MANUAL> "
MANUAL> Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.5.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 761, in main_loop
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.5.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 456, in process_stdin
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.5.1-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 425, in shlex_quotes
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
